version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps-actions
    groups:
      github-actions:
        patterns:
          - "*"
